#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : Botan
Version  : 2.18.2
Release  : 306
URL      : https://botan.randombit.net/releases/Botan-2.18.2.tar.xz
Source0  : https://botan.randombit.net/releases/Botan-2.18.2.tar.xz
Summary  : Crypto and TLS for C++11
Group    : Development/Tools
License  : GPL-2.0
Requires: Botan-bin = %{version}-%{release}
Requires: Botan-lib = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : bzip2-staticdev
BuildRequires : openssl-dev
BuildRequires : openssl-staticdev
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0002-Enable-genentropy-3-on-Linux.patch

%description
Botan: Crypto and TLS for Modern C++
========================================
Botan (Japanese for peony flower) is a C++ cryptography library released under the
permissive `Simplified BSD <https://botan.randombit.net/license.txt>`_ license.

%package bin
Summary: bin components for the Botan package.
Group: Binaries

%description bin
bin components for the Botan package.


%package dev
Summary: dev components for the Botan package.
Group: Development
Requires: Botan-lib = %{version}-%{release}
Requires: Botan-bin = %{version}-%{release}
Provides: Botan-devel = %{version}-%{release}
Requires: Botan = %{version}-%{release}

%description dev
dev components for the Botan package.


%package doc
Summary: doc components for the Botan package.
Group: Documentation

%description doc
doc components for the Botan package.


%package lib
Summary: lib components for the Botan package.
Group: Libraries

%description lib
lib components for the Botan package.


%package staticdev
Summary: staticdev components for the Botan package.
Group: Default
Requires: Botan-dev = %{version}-%{release}

%description staticdev
staticdev components for the Botan package.


%prep
%setup -q -n Botan-2.18.2
cd %{_builddir}/Botan-2.18.2
%patch1 -p1

%build
## build_prepend content
ln -sf configure.py configure
## build_prepend end
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639864898
## build_prepend content
ln -sf configure.py configure
## build_prepend end
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags_pgo content
## pgo generate
unset ASFLAGS
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage -fprofile-partial-training -fprofile-correction -freorder-functions --coverage -lgcov"
export CFLAGS_GENERATE="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export ASMFLAGS_GENERATE="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export FCFLAGS_GENERATE="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export FFLAGS_GENERATE="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export CXXFLAGS_GENERATE="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export LDFLAGS_GENERATE="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export LIBS_GENERATE="-lgcov"
## pgo use
## -fno-tree-vectorize: disable -ftree-vectorize thus disable -ftree-loop-vectorize and -ftree-slp-vectorize -fopt-info-vec
## -Ofast -ffast-math
## -funroll-loops maybe dangerous
## -Wl,-z,max-page-size=0x1000
## -pthread -lpthread
## -Wl,-Bsymbolic-functions
export PGO_USE="-Wmissing-profile -Wcoverage-mismatch -fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-partial-training -fprofile-correction -freorder-functions"
export CFLAGS_USE="-g3 -ggdb -Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export ASMFLAGS_USE="-g3 -ggdb -Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export FCFLAGS_USE="-g3 -ggdb -Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export FFLAGS_USE="-g3 -ggdb -Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export CXXFLAGS_USE="-g3 -ggdb -Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export LDFLAGS_USE="-g3 -ggdb -Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
#
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
#
export LD_LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="/usr/local/cuda/include"
#
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=1
export __GL_SYNC_DISPLAY_DEVICE=HDMI-0
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=HDMI-0
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
## altflags_pgo end
if [ ! -f statuspgo ]; then
echo PGO Phase 1
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
export ASMFLAGS="${ASMFLAGS_GENERATE}"
export LIBS="${LIBS_GENERATE}"
./configure --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/bin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/usr/com --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-static --enable-modules=bzip2,zlib,openssl,lzma
## make_prepend64 content
find . -type f -name 'Makefile' -exec sed -i 's:-lbz2\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libbz2.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lz\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libz.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-llzma\b:-Wl,--whole-archive,--as-needed,/usr/lib64/liblzma.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lcrypto\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libcrypto.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lssl\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libssl.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
## make_prepend64 end
make  %{?_smp_mflags}    V=1 VERBOSE=1

## profile_payload start
unset LD_LIBRARY_PATH
unset LIBRARY_PATH
make -j1 VERBOSE=1 V=1 check || :
export LD_LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
## profile_payload end
make clean || :
echo USED > statuspgo
fi
if [ -f statuspgo ]; then
echo PGO Phase 2
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
export ASMFLAGS="${ASMFLAGS_USE}"
export LIBS="${LIBS_USE}"
./configure --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/bin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/usr/com --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-static --enable-modules=bzip2,zlib,openssl,lzma
## make_prepend64 content
find . -type f -name 'Makefile' -exec sed -i 's:-lbz2\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libbz2.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lz\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libz.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-llzma\b:-Wl,--whole-archive,--as-needed,/usr/lib64/liblzma.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lcrypto\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libcrypto.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lssl\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libssl.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
## make_prepend64 end
make  %{?_smp_mflags}    V=1 VERBOSE=1
fi


%install
export SOURCE_DATE_EPOCH=1639864898
rm -rf %{buildroot}
## install_prepend content
sed -i 's/env python/env python3/' src/scripts/install.py
## install_prepend end
%make_install
## install_append content
sed -e '1{/^#!/d}' -i %{buildroot}/usr/lib64/python*/site-packages/botan2.py
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/botan

%files dev
%defattr(-,root,root,-)
/usr/include/botan-2/botan/adler32.h
/usr/include/botan-2/botan/aead.h
/usr/include/botan-2/botan/aes.h
/usr/include/botan-2/botan/alg_id.h
/usr/include/botan-2/botan/argon2.h
/usr/include/botan-2/botan/aria.h
/usr/include/botan-2/botan/asn1_alt_name.h
/usr/include/botan-2/botan/asn1_attribute.h
/usr/include/botan-2/botan/asn1_obj.h
/usr/include/botan-2/botan/asn1_oid.h
/usr/include/botan-2/botan/asn1_print.h
/usr/include/botan-2/botan/asn1_str.h
/usr/include/botan-2/botan/asn1_time.h
/usr/include/botan-2/botan/assert.h
/usr/include/botan-2/botan/auto_rng.h
/usr/include/botan-2/botan/b64_filt.h
/usr/include/botan-2/botan/base32.h
/usr/include/botan-2/botan/base58.h
/usr/include/botan-2/botan/base64.h
/usr/include/botan-2/botan/basefilt.h
/usr/include/botan-2/botan/bcrypt.h
/usr/include/botan-2/botan/bcrypt_pbkdf.h
/usr/include/botan-2/botan/ber_dec.h
/usr/include/botan-2/botan/bigint.h
/usr/include/botan-2/botan/blake2b.h
/usr/include/botan-2/botan/blinding.h
/usr/include/botan-2/botan/block_cipher.h
/usr/include/botan-2/botan/blowfish.h
/usr/include/botan-2/botan/botan.h
/usr/include/botan-2/botan/bswap.h
/usr/include/botan-2/botan/buf_comp.h
/usr/include/botan-2/botan/buf_filt.h
/usr/include/botan-2/botan/build.h
/usr/include/botan-2/botan/bzip2.h
/usr/include/botan-2/botan/calendar.h
/usr/include/botan-2/botan/camellia.h
/usr/include/botan-2/botan/cascade.h
/usr/include/botan-2/botan/cast128.h
/usr/include/botan-2/botan/cast256.h
/usr/include/botan-2/botan/cbc.h
/usr/include/botan-2/botan/cbc_mac.h
/usr/include/botan-2/botan/ccm.h
/usr/include/botan-2/botan/cecpq1.h
/usr/include/botan-2/botan/cert_status.h
/usr/include/botan-2/botan/certstor.h
/usr/include/botan-2/botan/certstor_flatfile.h
/usr/include/botan-2/botan/certstor_sql.h
/usr/include/botan-2/botan/certstor_system.h
/usr/include/botan-2/botan/cfb.h
/usr/include/botan-2/botan/chacha.h
/usr/include/botan-2/botan/chacha20poly1305.h
/usr/include/botan-2/botan/chacha_rng.h
/usr/include/botan-2/botan/charset.h
/usr/include/botan-2/botan/cipher_filter.h
/usr/include/botan-2/botan/cipher_mode.h
/usr/include/botan-2/botan/cmac.h
/usr/include/botan-2/botan/comb4p.h
/usr/include/botan-2/botan/comp_filter.h
/usr/include/botan-2/botan/compiler.h
/usr/include/botan-2/botan/compression.h
/usr/include/botan-2/botan/cpuid.h
/usr/include/botan-2/botan/crc24.h
/usr/include/botan-2/botan/crc32.h
/usr/include/botan-2/botan/credentials_manager.h
/usr/include/botan-2/botan/crl_ent.h
/usr/include/botan-2/botan/cryptobox.h
/usr/include/botan-2/botan/ctr.h
/usr/include/botan-2/botan/curve25519.h
/usr/include/botan-2/botan/curve_gfp.h
/usr/include/botan-2/botan/curve_nistp.h
/usr/include/botan-2/botan/data_snk.h
/usr/include/botan-2/botan/data_src.h
/usr/include/botan-2/botan/database.h
/usr/include/botan-2/botan/datastor.h
/usr/include/botan-2/botan/der_enc.h
/usr/include/botan-2/botan/des.h
/usr/include/botan-2/botan/desx.h
/usr/include/botan-2/botan/dh.h
/usr/include/botan-2/botan/divide.h
/usr/include/botan-2/botan/dl_algo.h
/usr/include/botan-2/botan/dl_group.h
/usr/include/botan-2/botan/dlies.h
/usr/include/botan-2/botan/dsa.h
/usr/include/botan-2/botan/dyn_load.h
/usr/include/botan-2/botan/eax.h
/usr/include/botan-2/botan/ec_group.h
/usr/include/botan-2/botan/ecc_key.h
/usr/include/botan-2/botan/ecdh.h
/usr/include/botan-2/botan/ecdsa.h
/usr/include/botan-2/botan/ecgdsa.h
/usr/include/botan-2/botan/ecies.h
/usr/include/botan-2/botan/eckcdsa.h
/usr/include/botan-2/botan/ed25519.h
/usr/include/botan-2/botan/elgamal.h
/usr/include/botan-2/botan/eme.h
/usr/include/botan-2/botan/eme_pkcs.h
/usr/include/botan-2/botan/eme_raw.h
/usr/include/botan-2/botan/emsa.h
/usr/include/botan-2/botan/emsa1.h
/usr/include/botan-2/botan/emsa_pkcs1.h
/usr/include/botan-2/botan/emsa_raw.h
/usr/include/botan-2/botan/emsa_x931.h
/usr/include/botan-2/botan/entropy_src.h
/usr/include/botan-2/botan/exceptn.h
/usr/include/botan-2/botan/fd_unix.h
/usr/include/botan-2/botan/ffi.h
/usr/include/botan-2/botan/filter.h
/usr/include/botan-2/botan/filters.h
/usr/include/botan-2/botan/fpe_fe1.h
/usr/include/botan-2/botan/gcm.h
/usr/include/botan-2/botan/gf2m_small_m.h
/usr/include/botan-2/botan/ghash.h
/usr/include/botan-2/botan/gmac.h
/usr/include/botan-2/botan/gost_28147.h
/usr/include/botan-2/botan/gost_3410.h
/usr/include/botan-2/botan/gost_3411.h
/usr/include/botan-2/botan/hash.h
/usr/include/botan-2/botan/hash_id.h
/usr/include/botan-2/botan/hex.h
/usr/include/botan-2/botan/hex_filt.h
/usr/include/botan-2/botan/hkdf.h
/usr/include/botan-2/botan/hmac.h
/usr/include/botan-2/botan/hmac_drbg.h
/usr/include/botan-2/botan/hotp.h
/usr/include/botan-2/botan/http_util.h
/usr/include/botan-2/botan/idea.h
/usr/include/botan-2/botan/init.h
/usr/include/botan-2/botan/iso9796.h
/usr/include/botan-2/botan/kasumi.h
/usr/include/botan-2/botan/kdf.h
/usr/include/botan-2/botan/kdf1.h
/usr/include/botan-2/botan/kdf1_iso18033.h
/usr/include/botan-2/botan/kdf2.h
/usr/include/botan-2/botan/keccak.h
/usr/include/botan-2/botan/key_constraint.h
/usr/include/botan-2/botan/key_filt.h
/usr/include/botan-2/botan/key_spec.h
/usr/include/botan-2/botan/keypair.h
/usr/include/botan-2/botan/lion.h
/usr/include/botan-2/botan/loadstor.h
/usr/include/botan-2/botan/locking_allocator.h
/usr/include/botan-2/botan/lookup.h
/usr/include/botan-2/botan/lzma.h
/usr/include/botan-2/botan/mac.h
/usr/include/botan-2/botan/mceies.h
/usr/include/botan-2/botan/mceliece.h
/usr/include/botan-2/botan/md4.h
/usr/include/botan-2/botan/md5.h
/usr/include/botan-2/botan/mdx_hash.h
/usr/include/botan-2/botan/mem_ops.h
/usr/include/botan-2/botan/mgf1.h
/usr/include/botan-2/botan/misty1.h
/usr/include/botan-2/botan/mode_pad.h
/usr/include/botan-2/botan/monty.h
/usr/include/botan-2/botan/mul128.h
/usr/include/botan-2/botan/mutex.h
/usr/include/botan-2/botan/name_constraint.h
/usr/include/botan-2/botan/newhope.h
/usr/include/botan-2/botan/nist_keywrap.h
/usr/include/botan-2/botan/noekeon.h
/usr/include/botan-2/botan/numthry.h
/usr/include/botan-2/botan/oaep.h
/usr/include/botan-2/botan/ocb.h
/usr/include/botan-2/botan/ocsp.h
/usr/include/botan-2/botan/ocsp_types.h
/usr/include/botan-2/botan/ofb.h
/usr/include/botan-2/botan/oids.h
/usr/include/botan-2/botan/otp.h
/usr/include/botan-2/botan/p11.h
/usr/include/botan-2/botan/p11_ecc_key.h
/usr/include/botan-2/botan/p11_ecdh.h
/usr/include/botan-2/botan/p11_ecdsa.h
/usr/include/botan-2/botan/p11_module.h
/usr/include/botan-2/botan/p11_object.h
/usr/include/botan-2/botan/p11_randomgenerator.h
/usr/include/botan-2/botan/p11_rsa.h
/usr/include/botan-2/botan/p11_session.h
/usr/include/botan-2/botan/p11_slot.h
/usr/include/botan-2/botan/p11_types.h
/usr/include/botan-2/botan/p11_x509.h
/usr/include/botan-2/botan/package.h
/usr/include/botan-2/botan/par_hash.h
/usr/include/botan-2/botan/parsing.h
/usr/include/botan-2/botan/passhash9.h
/usr/include/botan-2/botan/pbes2.h
/usr/include/botan-2/botan/pbkdf.h
/usr/include/botan-2/botan/pbkdf1.h
/usr/include/botan-2/botan/pbkdf2.h
/usr/include/botan-2/botan/pem.h
/usr/include/botan-2/botan/pgp_s2k.h
/usr/include/botan-2/botan/pipe.h
/usr/include/botan-2/botan/pk_algs.h
/usr/include/botan-2/botan/pk_keys.h
/usr/include/botan-2/botan/pk_ops.h
/usr/include/botan-2/botan/pk_ops_fwd.h
/usr/include/botan-2/botan/pkcs10.h
/usr/include/botan-2/botan/pkcs11.h
/usr/include/botan-2/botan/pkcs11f.h
/usr/include/botan-2/botan/pkcs11t.h
/usr/include/botan-2/botan/pkcs8.h
/usr/include/botan-2/botan/pkix_enums.h
/usr/include/botan-2/botan/pkix_types.h
/usr/include/botan-2/botan/point_gfp.h
/usr/include/botan-2/botan/poly1305.h
/usr/include/botan-2/botan/polyn_gf2m.h
/usr/include/botan-2/botan/pow_mod.h
/usr/include/botan-2/botan/prf_tls.h
/usr/include/botan-2/botan/prf_x942.h
/usr/include/botan-2/botan/processor_rng.h
/usr/include/botan-2/botan/psk_db.h
/usr/include/botan-2/botan/psk_db_sql.h
/usr/include/botan-2/botan/pssr.h
/usr/include/botan-2/botan/pubkey.h
/usr/include/botan-2/botan/pwdhash.h
/usr/include/botan-2/botan/rc4.h
/usr/include/botan-2/botan/rdrand_rng.h
/usr/include/botan-2/botan/reducer.h
/usr/include/botan-2/botan/rfc3394.h
/usr/include/botan-2/botan/rfc6979.h
/usr/include/botan-2/botan/rmd160.h
/usr/include/botan-2/botan/rng.h
/usr/include/botan-2/botan/rotate.h
/usr/include/botan-2/botan/roughtime.h
/usr/include/botan-2/botan/rsa.h
/usr/include/botan-2/botan/salsa20.h
/usr/include/botan-2/botan/scan_name.h
/usr/include/botan-2/botan/scrypt.h
/usr/include/botan-2/botan/secmem.h
/usr/include/botan-2/botan/secqueue.h
/usr/include/botan-2/botan/seed.h
/usr/include/botan-2/botan/serpent.h
/usr/include/botan-2/botan/sha160.h
/usr/include/botan-2/botan/sha2_32.h
/usr/include/botan-2/botan/sha2_64.h
/usr/include/botan-2/botan/sha3.h
/usr/include/botan-2/botan/shacal2.h
/usr/include/botan-2/botan/shake.h
/usr/include/botan-2/botan/shake_cipher.h
/usr/include/botan-2/botan/siphash.h
/usr/include/botan-2/botan/siv.h
/usr/include/botan-2/botan/skein_512.h
/usr/include/botan-2/botan/sm2.h
/usr/include/botan-2/botan/sm2_enc.h
/usr/include/botan-2/botan/sm3.h
/usr/include/botan-2/botan/sm4.h
/usr/include/botan-2/botan/sodium.h
/usr/include/botan-2/botan/sp800_108.h
/usr/include/botan-2/botan/sp800_56a.h
/usr/include/botan-2/botan/sp800_56c.h
/usr/include/botan-2/botan/srp6.h
/usr/include/botan-2/botan/stateful_rng.h
/usr/include/botan-2/botan/stl_compatibility.h
/usr/include/botan-2/botan/stream_cipher.h
/usr/include/botan-2/botan/stream_mode.h
/usr/include/botan-2/botan/streebog.h
/usr/include/botan-2/botan/sym_algo.h
/usr/include/botan-2/botan/symkey.h
/usr/include/botan-2/botan/system_rng.h
/usr/include/botan-2/botan/threefish.h
/usr/include/botan-2/botan/threefish_512.h
/usr/include/botan-2/botan/tiger.h
/usr/include/botan-2/botan/tls_alert.h
/usr/include/botan-2/botan/tls_algos.h
/usr/include/botan-2/botan/tls_blocking.h
/usr/include/botan-2/botan/tls_callbacks.h
/usr/include/botan-2/botan/tls_channel.h
/usr/include/botan-2/botan/tls_ciphersuite.h
/usr/include/botan-2/botan/tls_client.h
/usr/include/botan-2/botan/tls_exceptn.h
/usr/include/botan-2/botan/tls_extensions.h
/usr/include/botan-2/botan/tls_handshake_msg.h
/usr/include/botan-2/botan/tls_magic.h
/usr/include/botan-2/botan/tls_messages.h
/usr/include/botan-2/botan/tls_policy.h
/usr/include/botan-2/botan/tls_server.h
/usr/include/botan-2/botan/tls_server_info.h
/usr/include/botan-2/botan/tls_session.h
/usr/include/botan-2/botan/tls_session_manager.h
/usr/include/botan-2/botan/tls_session_manager_sql.h
/usr/include/botan-2/botan/tls_version.h
/usr/include/botan-2/botan/totp.h
/usr/include/botan-2/botan/tss.h
/usr/include/botan-2/botan/twofish.h
/usr/include/botan-2/botan/types.h
/usr/include/botan-2/botan/uuid.h
/usr/include/botan-2/botan/version.h
/usr/include/botan-2/botan/whrlpool.h
/usr/include/botan-2/botan/workfactor.h
/usr/include/botan-2/botan/x509_ca.h
/usr/include/botan-2/botan/x509_crl.h
/usr/include/botan-2/botan/x509_dn.h
/usr/include/botan-2/botan/x509_ext.h
/usr/include/botan-2/botan/x509_key.h
/usr/include/botan-2/botan/x509_obj.h
/usr/include/botan-2/botan/x509cert.h
/usr/include/botan-2/botan/x509path.h
/usr/include/botan-2/botan/x509self.h
/usr/include/botan-2/botan/x919_mac.h
/usr/include/botan-2/botan/xmss.h
/usr/include/botan-2/botan/xmss_hash.h
/usr/include/botan-2/botan/xmss_key_pair.h
/usr/include/botan-2/botan/xmss_parameters.h
/usr/include/botan-2/botan/xmss_privatekey.h
/usr/include/botan-2/botan/xmss_publickey.h
/usr/include/botan-2/botan/xmss_wots.h
/usr/include/botan-2/botan/xmss_wots_parameters.h
/usr/include/botan-2/botan/xmss_wots_privatekey.h
/usr/include/botan-2/botan/xmss_wots_publickey.h
/usr/include/botan-2/botan/xtea.h
/usr/include/botan-2/botan/xts.h
/usr/include/botan-2/botan/zlib.h
/usr/lib64/libbotan-2.so
/usr/lib64/pkgconfig/botan-2.pc
/usr/lib64/python3.10/site-packages/botan2.py

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/botan-2.18.2/authors.txt
/usr/share/doc/botan-2.18.2/handbook/abi.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/bigint.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/block_cipher.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/cipher_modes.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/compression.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/contents.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/credentials_manager.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/cryptobox.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/ecc.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/env_vars.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/ffi.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/filters.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/fpe.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/hash.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/kdf.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/keywrap.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/message_auth_codes.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/otp.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/passhash.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/pbkdf.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/pkcs11.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/psk_db.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/pubkey.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/python.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/rng.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/roughtime.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/secmem.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/srp.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/stream_ciphers.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/tls.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/tpm.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/tss.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/versions.rst
/usr/share/doc/botan-2.18.2/handbook/api_ref/x509.rst
/usr/share/doc/botan-2.18.2/handbook/authors.txt
/usr/share/doc/botan-2.18.2/handbook/building.rst
/usr/share/doc/botan-2.18.2/handbook/cli.rst
/usr/share/doc/botan-2.18.2/handbook/contents.rst
/usr/share/doc/botan-2.18.2/handbook/credits.rst
/usr/share/doc/botan-2.18.2/handbook/deprecated.rst
/usr/share/doc/botan-2.18.2/handbook/dev_ref/configure.rst
/usr/share/doc/botan-2.18.2/handbook/dev_ref/contents.rst
/usr/share/doc/botan-2.18.2/handbook/dev_ref/continuous_integration.rst
/usr/share/doc/botan-2.18.2/handbook/dev_ref/contributing.rst
/usr/share/doc/botan-2.18.2/handbook/dev_ref/fuzzing.rst
/usr/share/doc/botan-2.18.2/handbook/dev_ref/mistakes.rst
/usr/share/doc/botan-2.18.2/handbook/dev_ref/oids.rst
/usr/share/doc/botan-2.18.2/handbook/dev_ref/os.rst
/usr/share/doc/botan-2.18.2/handbook/dev_ref/reading_list.rst
/usr/share/doc/botan-2.18.2/handbook/dev_ref/release_process.rst
/usr/share/doc/botan-2.18.2/handbook/dev_ref/test_framework.rst
/usr/share/doc/botan-2.18.2/handbook/dev_ref/todo.rst
/usr/share/doc/botan-2.18.2/handbook/goals.rst
/usr/share/doc/botan-2.18.2/handbook/index.rst
/usr/share/doc/botan-2.18.2/handbook/old_news.rst
/usr/share/doc/botan-2.18.2/handbook/packaging.rst
/usr/share/doc/botan-2.18.2/handbook/pgpkey.txt
/usr/share/doc/botan-2.18.2/handbook/roadmap.rst
/usr/share/doc/botan-2.18.2/handbook/security.rst
/usr/share/doc/botan-2.18.2/handbook/side_channels.rst
/usr/share/doc/botan-2.18.2/handbook/support.rst
/usr/share/doc/botan-2.18.2/license.txt
/usr/share/doc/botan-2.18.2/news.txt
/usr/share/doc/botan-2.18.2/pgpkey.txt

%files lib
%defattr(-,root,root,-)
/usr/lib64/libbotan-2.so.18
/usr/lib64/libbotan-2.so.18.18.2

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libbotan-2.a
